import type { Bid, Flight, Rules, SeatCell } from "./types";

export const FLIGHTS_DATA: Flight[] = [
  {
    id: "HY 602",
    from: "TAS",
    to: "IST",
    dep: "15 июн 08:45",
    arr: "11:20",
    duration: "5ч 35м",
    aircraft: "A321",
    bcFree: 2,
    bcTotal: 16,
    bids: 28,
    topBid: 620,
    revenue: 1180,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 814",
    from: "TAS",
    to: "DXB",
    dep: "15 июн 14:30",
    arr: "17:15",
    duration: "4ч 45м",
    aircraft: "B787",
    bcFree: 8,
    bcTotal: 24,
    bids: 11,
    topBid: 480,
    revenue: 3840,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 233",
    from: "TAS",
    to: "MOW",
    dep: "15 июн 11:15",
    arr: "13:30",
    duration: "3ч 15м",
    aircraft: "A320",
    bcFree: 0,
    bcTotal: 8,
    bids: 43,
    topBid: 390,
    revenue: 0,
    status: "sold",
    haul: "short",
  },
  {
    id: "HY 177",
    from: "TAS",
    to: "FRA",
    dep: "16 июн 06:00",
    arr: "09:45",
    duration: "7ч 45м",
    aircraft: "B767",
    bcFree: 14,
    bcTotal: 20,
    bids: 5,
    topBid: 550,
    revenue: 7700,
    status: "upcoming",
    haul: "long",
  },
  {
    id: "HY 409",
    from: "TAS",
    to: "PEK",
    dep: "16 июн 09:20",
    arr: "15:50",
    duration: "5ч 30м",
    aircraft: "A330",
    bcFree: 6,
    bcTotal: 18,
    bids: 19,
    topBid: 510,
    revenue: 3060,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 551",
    from: "TAS",
    to: "ICN",
    dep: "16 июн 13:00",
    arr: "22:15",
    duration: "6ч 15м",
    aircraft: "B787",
    bcFree: 3,
    bcTotal: 20,
    bids: 31,
    topBid: 540,
    revenue: 1620,
    status: "active",
    haul: "long",
  },
  {
    id: "HY 088",
    from: "TAS",
    to: "LHR",
    dep: "17 июн 00:30",
    arr: "05:20",
    duration: "8ч 50м",
    aircraft: "B767",
    bcFree: 10,
    bcTotal: 16,
    bids: 2,
    topBid: 600,
    revenue: 6000,
    status: "upcoming",
    haul: "ultra",
  },
  {
    id: "HY 312",
    from: "TAS",
    to: "ALA",
    dep: "15 июн 16:45",
    arr: "17:35",
    duration: "1ч 05м",
    aircraft: "A319",
    bcFree: 4,
    bcTotal: 8,
    bids: 7,
    topBid: 95,
    revenue: 380,
    status: "active",
    haul: "ultra-short",
  },
];

export const FALLBACK_FLIGHT: Flight = {
  id: "HY 000",
  from: "TAS",
  to: "TAS",
  dep: "—",
  arr: "—",
  duration: "—",
  aircraft: "—",
  bcFree: 0,
  bcTotal: 0,
  bids: 0,
  topBid: 0,
  revenue: 0,
  status: "upcoming",
  haul: "ultra-short",
};

export const INITIAL_BIDS: Bid[] = [
  {
    id: 1,
    name: "Иванов А.П.",
    tier: "Platinum",
    bid: 620,
    mult: 1.1,
    channel: "Email",
    time: "09:14",
    state: "pending",
  },
  {
    id: 2,
    name: "Ли Вэй",
    tier: "Gold",
    bid: 520,
    mult: 1.05,
    channel: "App",
    time: "13:07",
    state: "pending",
  },
  {
    id: 3,
    name: "Петрова М.С.",
    tier: "Silver",
    bid: 490,
    mult: 1.03,
    channel: "Email",
    time: "10:21",
    state: "pending",
  },
  {
    id: 4,
    name: "Smith J.",
    tier: "Standard",
    bid: 580,
    mult: 1.0,
    channel: "MMB",
    time: "11:32",
    state: "pending",
  },
  {
    id: 5,
    name: "Karimov B.",
    tier: "Platinum",
    bid: 400,
    mult: 1.1,
    channel: "Web",
    time: "08:55",
    state: "pending",
  },
  {
    id: 6,
    name: "Ahmadov F.",
    tier: "Standard",
    bid: 470,
    mult: 1.0,
    channel: "Email",
    time: "14:45",
    state: "pending",
  },
  {
    id: 7,
    name: "Brown T.",
    tier: "Gold",
    bid: 380,
    mult: 1.05,
    channel: "MMB",
    time: "07:30",
    state: "pending",
  },
  {
    id: 8,
    name: "Назаров О.",
    tier: "Standard",
    bid: 310,
    mult: 1.0,
    channel: "Web",
    time: "16:02",
    state: "pending",
  },
  {
    id: 9,
    name: "Юсупова Д.",
    tier: "Silver",
    bid: 345,
    mult: 1.03,
    channel: "Email",
    time: "15:18",
    state: "pending",
  },
  {
    id: 10,
    name: "Kim S.",
    tier: "Gold",
    bid: 430,
    mult: 1.05,
    channel: "App",
    time: "12:00",
    state: "pending",
  },
];

export const SEAT_MAP_BC: Array<Array<SeatCell | null>> = [
  [
    { id: "1A", taken: true },
    { id: "1C", taken: true },
    null,
    { id: "1D", taken: true },
    { id: "1F", taken: true },
  ],
  [
    { id: "2A", taken: true },
    { id: "2C", taken: true },
    null,
    { id: "2D", taken: true },
    { id: "2F", taken: true },
  ],
  [
    { id: "3A", taken: true },
    { id: "3C", taken: true },
    null,
    { id: "3D", taken: true },
    { id: "3F", taken: true },
  ],
  [
    { id: "4A", taken: false, bid: true },
    { id: "4C", taken: true },
    null,
    { id: "4D", taken: true },
    { id: "4F", taken: false, bid: true },
  ],
];

export const DEFAULT_RULES: Rules = {
  inviteDaysBefore: 14,
  chaserHoursBefore: 48,
  closureHoursBefore: 4,
  autoFulfillment: true,
  requirePurchased: true,
  blindBids: true,
  maxUpgradesPerFlight: 0,
  multiplierPlatinum: 10,
  multiplierGold: 5,
  multiplierSilver: 3,
  minBcUltraShort: 93,
  minBcShort: 118,
  minBcMedium: 262,
  minBcLong: 500,
  minBcUltraLong: 569,
  minExitShort: 8,
  minExitMedium: 32,
  minExitLong: 35,
  minSeatBlockShort: 8,
  minSeatBlockMedium: 32,
  minSeatBlockLong: 35,
  channels: { email: true, mmb: true, app: true, web: true, webcheckin: true, pushNotif: true },
  paymentMethods: { visa: true, mastercard: true, amex: true, jcb: false, diners: false },
  use3ds: false,
  continuousPricing: true,
  crossAirlineUpgrades: false,
  payWithPoints: false,
  seatBlocker: true,
};

export const weighted = (b: Bid) => Math.round(b.bid * b.mult);
